live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]
#working_directory = "~/Working"

[window]
decorations = "Buttonless"
padding = { x = 4, y = 4 }
opacity = 0.8

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[env]
TERM = "xterm-256color"

[debug]
render_timer = false
renderer = "glsl3"
prefer_egl = false
